spring:
  # OAuth 로그인
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 963970424928-bqjdhn97b38l8p8nr7oci2v0od4cvpdc.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

          kakao:
            client-id: d242caacaeef4e7e50acc0b0df1bec34
            client-secret: 발급받은 Client Secret 코드
            scope:
              - account_email
              - profile_nickname
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:14641/login/oauth2/code/kakao
            client-name: Kakao
            client-authentication-method: POST

          naver:
            client-id: IFjmF7UmaSj1zMNfeW7_
            client-secret: 4o4O8cY59C
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:14641/login/oauth2/code/naver

          facebook:
            client-id: 591119156507678
            client-secret: d5fee1be1bd1b978fbb6285ef1f9d334
            scope:
              - email
              - public_profile

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response